apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wgdv77oup-dotnet-basic 
  janus-idp.io/tekton: wgdv77oup-dotnet-basic
  backstage.io/kubernetes-id: wgdv77oup-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgdv77oup-dotnet-basic
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml